Error Corregido
TypeError: fitness() missing 7 required positional arguments: 'filters1', 'filters2', 'filters3', 'filters4', 'kernel', 'maxpool1', and 'maxpool2'